# Fomage Application Configuration

# Server settings
server:
  port: ${SERVER_PORT:8080}
  address: ${SERVER_HOST:0.0.0.0}

# Spring settings
spring:
  application:
    name: ${APP_NAME:Fomage}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:fomage}
      auto-index-creation: true

# Logging configuration
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    net.kigawa.fomage: ${LOG_LEVEL:INFO}
    org.springframework: INFO
    org.mongodb: INFO

# Security settings
fomage:
  security:
    enabled: ${SECURITY_ENABLED:true}
    api-key: ${API_KEY_SECRET:default-secret-key}

# Environment settings
environment: ${ENVIRONMENT:development}

# Application version
app:
  version: ${APP_VERSION:1.0.0}