# Fomage API Configuration

# API settings
api:
  version: ${API_VERSION:1.0.0}
  base-path: /api
  rate-limit:
    enabled: ${API_RATE_LIMIT_ENABLED:true}
    max-requests: ${API_RATE_LIMIT_MAX:100}
    time-window: ${API_RATE_LIMIT_WINDOW:60}  # in seconds

# Security settings
fomage:
  security:
    enabled: ${SECURITY_ENABLED:true}
    api-key: ${API_KEY_SECRET:default-secret-key}

# Logging configuration specific to API
logging:
  level:
    net.kigawa.fomage.api: ${LOG_LEVEL:INFO}